version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: mrzara/lab4-examples:compose-django
    container_name: compose-django
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.2
    image: mrzara/lab4-examples:compose-monitoring
    container_name: compose-monitoring
    network_mode: "host"
